name: 'LoadFromSpringCloudConfigServer'
description: 'Sets Env and Secrets from a Spring Cloud Config Server'

inputs:
  use_as_token_for_github_octokit:
    description: 'Use as the PAT Token to set secretss'
    required: false
    type: string
  token_for_github_octokit:
    description: 'Token for secrets'
    optional: true
    type: string
  config_server_oauth_token_endpoint:
    description: 'Auth Token Endpoint'
    required: false
    type: string
  config_server_oauth_client_id:
    description: 'OAuth2 ClientId'
    required: false
    type: string
  config_server_oauth_client_secret:
    description: 'OAuth2 Secret'
    required: false
    type: string

  config_server_base_url:
    description: 'Base URL of cloud config server'
    required: true
    type: string
  path:
    description: 'Path on cloud config server'
    required: true
    type: string
  propertytoretrieve:
    description: 'Property to retrieve'
    required: true
    type: string

  variabletoset:
    description: 'variable to set.  Will use propertytoretrieve if nothing is set'
    optional: true
    type: string
  # maskassecret:
  #   description: 'Mask as a secret?'
  #   optional: true
  #   type: boolean
  #   default: 'false'
  outputasenvvar:
    description: 'Output as a env var'
    optional: true
    type: boolean
  outputassecret:
    description: 'Output as a secret'
    optional: true
    type: boolean
  decodebase64:
    description: 'If a value starts with base64: convert it'
    required: false
    type: boolean

runs:
  using: 'node20'
  main: 'dist/index.js'
