name: Build
on: 
  workflow_dispatch:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
          cache: npm
      - run: npm i
      - run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v5
